AWSTemplateFormatVersion: "2010-09-09"
Description: Main Stack for Shamlin Web App - Nested CloudFormation

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
  PrivateSubnet1Cidr:
    Type: String
    Default: 10.0.3.0/24
  PrivateSubnet2Cidr:
    Type: String
    Default: 10.0.4.0/24
  AZ1:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a
  AZ2:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1b

Resources:

  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cf-templates-10u308snxiy7m-us-east-1/2025-10-03T110455.992Z03l-networking.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr
        AZ1: !Ref AZ1
        AZ2: !Ref AZ2

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cf-templates-10u308snxiy7m-us-east-1/2025-10-03T111819.247Zifj-security.yaml
      Parameters:
        VpcId: !ImportValue VPC-ID

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/cf-templates-10u308snxiy7m-us-east-1/2025-10-03T110939.158Zikl-compute.yaml
      Parameters:
        VpcId: !ImportValue VPC-ID
        PublicSubnet1: !Select [0, !Split [",", !ImportValue PublicSubnetIDs]]
        PublicSubnet2: !Select [1, !Split [",", !ImportValue PublicSubnetIDs]]
        PrivateSubnet1: !Select [0, !Split [",", !ImportValue PrivateSubnetIDs]]
        PrivateSubnet2: !Select [1, !Split [",", !ImportValue PrivateSubnetIDs]]
        ALBSecurityGroup: !ImportValue Shamlin-ALBSG
        EC2SecurityGroup: !ImportValue Shamlin-EC2SG
        InstanceProfile: !ImportValue Shamlin-EC2InstanceProfile
